version: "3"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  traefik:
    image: ${TRAEFIK_IMAGE}
    container_name: ${TRAEFIK_NAME}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML}:/traefik.toml:ro
      - ${TRAEFIK_ACME}:/acme.json
    networks:
      - frontend
    environment:
      - OVH_ENDPOINT
      - OVH_APPLICATION_KEY
      - OVH_APPLICATION_SECRET
      - OVH_CONSUMER_KEY
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:traefik.mysite.com
      - traefik.docker.network=common_frontend
      - traefik.port=8080
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_HTTPS_PORT}:443
      - ${TRAEFIK_API_PORT}:8080
    depends_on:
        - nextcloud

  nextcloud:
    image: ${NEXTCLOUD_IMAGE}
    container_name: ${NEXTCLOUD_NAME}
    restart: unless-stopped
    volumes:
      - ${NEXTCLOUD_VOL}:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:nextcloud.mysite.com
      - traefik.docker.network=common_frontend
      - traefik.port=80
    environment:
      - MYSQL_DATABASE=${NEXTCLOUD_DB}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_HOST=${MYSQL_NAME}:3306
      - NEXTCLOUD_TABLE_PREFIX=${NEXTCLOUD_DB_PREFIX}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_PASSWORD}
    networks:
      - backend
      - frontend
    ports:
        - ${NEXTCLOUD_PORT}:80
    depends_on:
      - mysql

  mysql:
    container_name: ${MYSQL_NAME}
    image: ${MYSQL_IMAGE}
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - NEXTCLOUD_DB
      - NEXTCLOUD_DB_USER
      - NEXTCLOUD_DB_PASSWORD
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_VOL}:/var/lib/mysql
      - ${MYSQL_ENTRY}:/docker-entrypoint-initdb.d/default.sql
    networks:
      - backend
    labels:
      - traefik.enable=false
